import type { ChecklistTemplate } from "./types";

export const checklistTemplates: ChecklistTemplate[] = [
  {
    id: "kitchen-opening",
    name: "Kitchen Opening & Line Setup",
    description:
      "Pre-service kitchen audit — equipment, temps, and line readiness before service.",
    category: "opening",
    schedule: "daily",
    estimatedMinutes: 20,
    items: [
      {
        id: "ko-1",
        title: "Hand wash sink stocked — soap, towels, sanitizer",
        type: "checkbox",
        required: true,
      },
      {
        id: "ko-2",
        title: "Walk-in cooler temperature",
        type: "temperature",
        required: true,
        minTemp: 33,
        maxTemp: 41,
        trainingNote: "Log before any food leaves the cooler.",
      },
      {
        id: "ko-3",
        title: "Hot line equipment preheated and operational",
        type: "yes_no",
        required: true,
        description: "Grill, fryers, holding cabinets at temp.",
      },
      {
        id: "ko-4",
        title: "Prep surfaces sanitized",
        type: "photo",
        required: true,
        description: "Photo of main prep line after sanitizer wipe-down.",
      },
      {
        id: "ko-5",
        title: "Date labels checked on all open prep",
        type: "checkbox",
        required: true,
      },
      {
        id: "ko-6",
        title: "Opening manager sign-off notes",
        type: "text",
        required: false,
      },
    ],
  },
  {
    id: "hot-line-temps",
    name: "Hot Line Temperature Check",
    description: "Per-shift hot holding and cooking temperature verification.",
    category: "food_safety",
    schedule: "per_shift",
    estimatedMinutes: 10,
    items: [
      {
        id: "hl-1",
        title: "Grill surface / flat top temp",
        type: "temperature",
        required: true,
        minTemp: 350,
        maxTemp: 450,
      },
      {
        id: "hl-2",
        title: "Hot holding cabinet #1",
        type: "temperature",
        required: true,
        minTemp: 135,
        maxTemp: 165,
      },
      {
        id: "hl-3",
        title: "Hot holding cabinet #2",
        type: "temperature",
        required: true,
        minTemp: 135,
        maxTemp: 165,
      },
      {
        id: "hl-4",
        title: "All hot-held items above 135°F",
        type: "yes_no",
        required: true,
        trainingNote: "Reheat or discard anything below 135°F for over 4 hours.",
      },
      {
        id: "hl-5",
        title: "Thermometer calibrated today",
        type: "checkbox",
        required: true,
      },
    ],
  },
  {
    id: "prep-cooler-log",
    name: "Prep Cooler & Walk-in Log",
    description: "Cold storage audit for prep coolers, walk-ins, and reach-ins.",
    category: "food_safety",
    schedule: "per_shift",
    estimatedMinutes: 12,
    items: [
      {
        id: "pc-1",
        title: "Walk-in cooler temperature",
        type: "temperature",
        required: true,
        minTemp: 33,
        maxTemp: 41,
      },
      {
        id: "pc-2",
        title: "Prep cooler #1 temperature",
        type: "temperature",
        required: true,
        minTemp: 33,
        maxTemp: 41,
      },
      {
        id: "pc-3",
        title: "Prep cooler #2 temperature",
        type: "temperature",
        required: true,
        minTemp: 33,
        maxTemp: 41,
      },
      {
        id: "pc-4",
        title: "FIFO rotation verified — no expired product",
        type: "yes_no",
        required: true,
      },
      {
        id: "pc-5",
        title: "Cooler organization photo",
        type: "photo",
        required: true,
      },
    ],
  },
  {
    id: "dish-sanitation",
    name: "Dish & Sanitation Station",
    description: "Three-compartment sink, dishwasher, and sanitizer concentration check.",
    category: "cleaning",
    schedule: "per_shift",
    estimatedMinutes: 15,
    items: [
      {
        id: "ds-1",
        title: "Dishwasher wash temp ≥ 150°F",
        type: "temperature",
        required: true,
        minTemp: 150,
        maxTemp: 180,
      },
      {
        id: "ds-2",
        title: "Sanitizer concentration (ppm)",
        type: "number",
        required: true,
        description: "Quat sanitizer: 150–400 ppm. Chlorine: 50–100 ppm.",
        trainingNote: "Test strips required every 4 hours.",
      },
      {
        id: "ds-3",
        title: "Three-compartment sink set up correctly",
        type: "yes_no",
        required: true,
      },
      {
        id: "ds-4",
        title: "Floor drains clear and mopped",
        type: "checkbox",
        required: true,
      },
      {
        id: "ds-5",
        title: "Dish area photo after cleaning",
        type: "photo",
        required: true,
      },
    ],
  },
  {
    id: "receiving-inspection",
    name: "Receiving & Storage Inspection",
    description: "Incoming delivery audit — temps, packaging, and labeling.",
    category: "audit",
    schedule: "daily",
    estimatedMinutes: 15,
    items: [
      {
        id: "ri-1",
        title: "Delivery truck / product temperature acceptable",
        type: "yes_no",
        required: true,
        trainingNote: "Reject product above 41°F for refrigerated items.",
      },
      {
        id: "ri-2",
        title: "Packaging intact — no leaks or pest evidence",
        type: "yes_no",
        required: true,
      },
      {
        id: "ri-3",
        title: "All items labeled with receive date",
        type: "checkbox",
        required: true,
      },
      {
        id: "ri-4",
        title: "Invoice matched to delivery",
        type: "checkbox",
        required: true,
      },
      {
        id: "ri-5",
        title: "Receiving log notes / issues",
        type: "text",
        required: false,
      },
    ],
  },
  {
    id: "equipment-safety",
    name: "Equipment Safety & PM Check",
    description: "Weekly equipment inspection — hood, fire suppression, sharp tools.",
    category: "audit",
    schedule: "weekly",
    estimatedMinutes: 20,
    items: [
      {
        id: "es-1",
        title: "Exhaust hood and filters clean",
        type: "yes_no",
        required: true,
      },
      {
        id: "es-2",
        title: "Fire suppression tag current",
        type: "checkbox",
        required: true,
        trainingNote: "Tag must be within 6 months of inspection.",
      },
      {
        id: "es-3",
        title: "Knives and slicers sanitized and stored",
        type: "checkbox",
        required: true,
      },
      {
        id: "es-4",
        title: "GFI outlets tested near wet areas",
        type: "yes_no",
        required: true,
      },
      {
        id: "es-5",
        title: "Equipment issues found (count)",
        type: "number",
        required: true,
        description: "Enter 0 if none.",
      },
      {
        id: "es-6",
        title: "Photo of hood / filter condition",
        type: "photo",
        required: false,
      },
    ],
  },
  {
    id: "manager-kitchen-audit",
    name: "Manager Kitchen Walk-through",
    description: "Daily manager audit — cleanliness, temps, staff compliance, and score.",
    category: "audit",
    schedule: "daily",
    estimatedMinutes: 25,
    items: [
      {
        id: "ma-1",
        title: "All staff wearing proper hair restraints",
        type: "yes_no",
        required: true,
      },
      {
        id: "ma-2",
        title: "Cross-contamination controls in place",
        type: "yes_no",
        required: true,
        description: "Separate boards, color-coded tools, raw below ready-to-eat.",
      },
      {
        id: "ma-3",
        title: "All required temp logs completed this shift",
        type: "yes_no",
        required: true,
      },
      {
        id: "ma-4",
        title: "Kitchen cleanliness score (1–10)",
        type: "number",
        required: true,
        minTemp: 1,
        maxTemp: 10,
      },
      {
        id: "ma-5",
        title: "Critical violations found",
        type: "text",
        required: false,
        description: "List any items requiring immediate corrective action.",
      },
      {
        id: "ma-6",
        title: "Walk-through photo evidence",
        type: "photo",
        required: true,
      },
    ],
  },
  {
    id: "kitchen-closing",
    name: "Kitchen Closing & Shutdown",
    description: "End-of-service kitchen audit — breakdown, storage, and security.",
    category: "closing",
    schedule: "daily",
    estimatedMinutes: 25,
    items: [
      {
        id: "kc-1",
        title: "All hot equipment powered down safely",
        type: "checkbox",
        required: true,
        trainingNote: "Grill off, fryers filtered, hood lights off.",
      },
      {
        id: "kc-2",
        title: "Walk-in cooler closing temperature",
        type: "temperature",
        required: true,
        minTemp: 33,
        maxTemp: 41,
      },
      {
        id: "kc-3",
        title: "Freezer closing temperature",
        type: "temperature",
        required: true,
        minTemp: -10,
        maxTemp: 0,
      },
      {
        id: "kc-4",
        title: "All food labeled, covered, and stored",
        type: "yes_no",
        required: true,
      },
      {
        id: "kc-5",
        title: "Floors mopped — kitchen photo",
        type: "photo",
        required: true,
      },
      {
        id: "kc-6",
        title: "Trash removed and area sanitized",
        type: "checkbox",
        required: true,
      },
      {
        id: "kc-7",
        title: "Closing notes for opening crew",
        type: "text",
        required: false,
      },
    ],
  },
];

export function getTemplateById(id: string): ChecklistTemplate | undefined {
  return checklistTemplates.find((t) => t.id === id);
}
